### ISSUE TITLE
inference with nuScence mini dataset- Failed!!!!

### ISSUE THREAD

**Issue by mdfaheem786** [exiawsh/StreamPETR#1]
Hi,

Great work, much appreciated :)

i am facing issue with the inference of this model, 

- config : https://github.com/exiawsh/StreamPETR/blob/main/projects/configs/StreamPETR/stream_petr_vov_flash_800_bs2_seq_24e.py
- model  : https://github.com/exiawsh/storage/releases/download/v1.0/stream_petr_vov_flash_800_bs2_seq_24e.pth

my package are as below :-
flash-attn               0.2.8
torch                       1.12.1+cu116
torchaudio             0.12.1+cu116
torchvision             0.13.1+cu116

i am running on GPU 1080Ti, with cuda 11.6.

Error as below:-

  File "/media/ubuntu/data/git_downloads/StreamPETR/projects/mmdet3d_plugin/models/utils/attention.py", line 74, in forward
    output = flash_attn_unpadded_kvpacked_func(
  File "/media/ubuntu/data/envs/streampetr/lib/python3.10/site-packages/flash_attn/flash_attn_interface.py", line 299, in flash_attn_unpadded_kvpacked_func
    return FlashAttnKVPackedFunc.apply(q, kv, cu_seqlens_q, cu_seqlens_k,
  File "/media/ubuntu/data/envs/streampetr/lib/python3.10/site-packages/flash_attn/flash_attn_interface.py", line 96, in forward
    out, softmax_lse, S_dmask = _flash_attn_forward(
  File "/media/ubuntu/data/envs/streampetr/lib/python3.10/site-packages/flash_attn/flash_attn_interface.py", line 21, in _flash_attn_forward
    softmax_lse, *rest = flash_attn_cuda.fwd(
RuntimeError: Expected is_sm8x || is_sm75 to be true, but got false.  (Could this error message be improved?  If so, please report an enhancement request to PyTorch.)

kindly let me know if any where am i doing wrong, correct me if so.

Thanking you in advance :)

**Comment by exiawsh** [comment]
Hello, flash-attn do not support 1080Ti GPU currently. You need to make some modifications to the config:
change the config here 
https://github.com/exiawsh/StreamPETR/blob/5808a554c69ca104bb05da53297edfee49364a2b/projects/configs/StreamPETR/stream_petr_r50_flash_704_bs2_seq_24e.py#L111

to dict(type='PETRMultiheadAttention', embed_dims=256, num_heads=8, dropout=0.1, fp16=True,).

**Comment by mdfaheem786** [comment]
thank you so much @exiawsh for the quick resposes.

will try with normal multiheadattention rather flashattention.

thank you :)

**Comment by exiawsh** [comment]
Thank you for your attention, feel free to contact us.

**Comment by furyNerd** [comment]
hi, @mdfaheem786  have you succeed make the inference? could share your command or script to do the inference? thanks so much

i tried `mono_det_demo.py` of `mmdet3d` in the docker container with env-configured as in docs, with 

```shell
export cam_ann=/StreamPETR/mmdetection3d/demo/data/kitti/kitti_000008_infos.pkl
export img_uri=/StreamPETR/mmdetection3d/demo/data/kitti/kitti_000008.png
export mdl_cfg=/StreamPETR/projects/configs/StreamPETR/stream_petr_vov_flash_800_bs2_seq_24e.py
export mdl_ckp=/StreamPETR/ckpts/stream_petr_vov_flash_800_bs2_seq_24e.pth # downloaded in advance
export out_dir=/StreamPETR/my_test/stream_petr_ki.png
python demo/mono_det_demo.py ${img_uri} ${cam_ann} ${mdl_cfg} ${mdl_ckp} --out-dir ${out_dir}
```

and i tried all possibles, alway got errors like:
```shell
(streampetr) root@4feaf720ae18:/StreamPETR/mmdetection3d# python demo/mono_det_demo.py ${img_uri} ${cam_ann} ${mdl_cfg} ${mdl_ckp} --out-dir ${out_dir}
Traceback (most recent call last):
  File "demo/mono_det_demo.py", line 46, in <module>
    main()
  File "demo/mono_det_demo.py", line 31, in main
    model = init_model(args.config, args.checkpoint, device=args.device)
  File "/StreamPETR/mmdetection3d/mmdet3d/apis/inference.py", line 60, in init_model
    model = build_model(config.model, test_cfg=config.get('test_cfg'))
  File "/StreamPETR/mmdetection3d/mmdet3d/models/builder.py", line 122, in build_model
    return build_detector(cfg, train_cfg=train_cfg, test_cfg=test_cfg)
  File "/StreamPETR/mmdetection3d/mmdet3d/models/builder.py", line 95, in build_detector
    return MMDET_DETECTORS.build(
  File "/root/miniconda3/envs/streampetr/lib/python3.8/site-packages/mmcv/utils/registry.py", line 237, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/root/miniconda3/envs/streampetr/lib/python3.8/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/root/miniconda3/envs/streampetr/lib/python3.8/site-packages/mmcv/utils/registry.py", line 61, in build_from_cfg
    raise KeyError(
KeyError: 'Petr3D is not in the models registry'
```
