### ISSUE TITLE
error of ViT-L

### ISSUE THREAD

**Issue by sven-x** [exiawsh/StreamPETR#100]
@exiawsh @yingfei1016 Thanks for your great job! I tried ViT-L on the 800x1600 input images according to your suggested config, but meets the following error during training.

```bash
Traceback (most recent call last):                                                                                                                                                         
  File "/usr/local/lib/python3.8/dist-packages/mmdet/core/bbox/assigners/sim_ota_assigner.py", line 67, in assign
    assign_result = self._assign(pred_scores, priors, decoded_bboxes,                                                                                                                      
  File "/usr/local/lib/python3.8/dist-packages/mmdet/core/bbox/assigners/sim_ota_assigner.py", line 172, in _assign
    self.dynamic_k_matching(                                                                                                                                                               
  File "/usr/local/lib/python3.8/dist-packages/mmdet/core/bbox/assigners/sim_ota_assigner.py", line 238, in dynamic_k_matching
    _, pos_idx = torch.topk(                                                                 
RuntimeError: CUDA error: device-side assert triggered                                                                                                                                     
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```

Do you have a similar experience? And how to resolve it? Thanks.

**Comment by yingfei1016** [comment]
This is the problem of sim-OTA. Have you try the original StreamPETR first instead of the deformable version?

**Comment by yingfei1016** [comment]
It seems the sim-OTA cost lot of resources when use the high resolution. In fact, the FPN scales in single-stage methods  always  from 8 (8, 16, 32, 64,128)  instead of 4 (4, 8, 16, 32, 64) . So you can try (8, 16, 32, 64,128) .

**Comment by yingfei1016** [comment]
For the first problem, I don't know. 
For the second problem,  we have not train the 1600x800 on val set.
