### ISSUE TITLE
Training error

### ISSUE THREAD

**Issue by wofeifeileni** [exiawsh/StreamPETR#146]
When I was training with the following code, this error occurred. May I ask where the error occurred? Can you help me
`tools/dist_train.sh projects/configs/StreamPETR/stream_petr_vov_flash_800_bs2_seq_24e.py 4 --work-dir work_dirs/stream_petr_vov_flash_800_bs2_seq_24e/`

Traceback (most recent call last):
  File "tools/train.py", line 263, in <module>
    main()
  File "tools/train.py", line 225, in main
    datasets = [build_dataset(cfg.data.train)]
  File "/root/autodl-tmp/StreamPETR/mmdetection3d/mmdet3d/datasets/builder.py", line 46, in build_dataset
    dataset = build_from_cfg(cfg, MMDET_DATASETS, default_args)
  File "/root/miniconda3/lib/python3.8/site-packages/mmcv/utils/registry.py", line 72, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
_pickle.UnpicklingError: CustomNuScenesDataset: pickle data was truncated
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/mmcv/utils/registry.py", line 69, in build_from_cfg
    return obj_cls(**args)
  File "/root/autodl-tmp/StreamPETR/projects/mmdet3d_plugin/datasets/nuscenes_dataset.py", line 30, in __init__
    super().__init__(*args, **kwargs)
  File "/root/autodl-tmp/StreamPETR/mmdetection3d/mmdet3d/datasets/nuscenes_dataset.py", line 131, in __init__
    super().__init__(
  File "/root/autodl-tmp/StreamPETR/mmdetection3d/mmdet3d/datasets/custom_3d.py", line 88, in __init__
    self.data_infos = self.load_annotations(open(local_path, 'rb'))
  File "/root/autodl-tmp/StreamPETR/mmdetection3d/mmdet3d/datasets/nuscenes_dataset.py", line 187, in load_annotations
    data = mmcv.load(ann_file, file_format='pkl')
  File "/root/miniconda3/lib/python3.8/site-packages/mmcv/fileio/io.py", line 70, in load
    obj = handler.load_from_fileobj(file, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/mmcv/fileio/handlers/pickle_handler.py", line 12, in load_from_fileobj
    return pickle.load(file, **kwargs)
_pickle.UnpicklingError: pickle data was truncated

**Comment by exiawsh** [comment]
Did you download the pkl file from our GitHub? It seems that there was data loss during downloading.

**Comment by wofeifeileni** [comment]
Yes, all the pkl files were downloaded from GitHub instead of being generated by running the code. Does this possibly cause file corruption

**Comment by exiawsh** [comment]
You need to check the size of your pkl file to ensure it matches GitHub's. 
Perhaps your download was interrupted, resulting in missing files.

**Comment by wofeifeileni** [comment]
Yes, there is indeed a file damage. Thank you for your timely and accurate reply.
I have another question to trouble you with. Previously, I copied some files from PETR project to the StreamPETR project and tried training, but the following problem occurred:

Original Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/autodl-tmp/StreamPETR/mmdetection3d/mmdet3d/datasets/custom_3d.py", line 435, in __getitem__
    data = self.prepare_train_data(idx)
  File "/root/autodl-tmp/StreamPETR/mmdetection3d/mmdet3d/datasets/custom_3d.py", line 229, in prepare_train_data
    example = self.pipeline(input_dict)
  File "/root/autodl-tmp/StreamPETR/mmdetection3d/mmdet3d/datasets/pipelines/compose.py", line 49, in __call__
    data = t(data)
  File "/root/autodl-tmp/StreamPETR/mmdetection3d/mmdet3d/datasets/pipelines/loading.py", line 48, in __call__
    [mmcv.imread(name, self.color_type) for name in filename], axis=-1)
  File "/root/autodl-tmp/StreamPETR/mmdetection3d/mmdet3d/datasets/pipelines/loading.py", line 48, in <listcomp>
    [mmcv.imread(name, self.color_type) for name in filename], axis=-1)
  File "/root/miniconda3/lib/python3.8/site-packages/mmcv/image/io.py", line 203, in imread
    img_bytes = file_client.get(img_or_path)
  File "/root/miniconda3/lib/python3.8/site-packages/mmcv/fileio/file_client.py", line 1014, in get
    return self.client.get(filepath)
  File "/root/miniconda3/lib/python3.8/site-packages/mmcv/fileio/file_client.py", line 535, in get
    with open(filepath, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/data/Dataset/nuScenes/samples/CAM_FRONT/n015-2018-10-08-15-52-24+0800__CAM_FRONT__1538985271762485.jpg'

I know this is caused by not being able to find the file，but I have already placed the dataset (StreamPETR/data/nuscenes) according to the StreamPETR project. Why does it still search for files under the path "/data/Dataset/nuScenes/"? This path seems to be the recommended path for the PETR project. Is this because I added new files?

**Comment by exiawsh** [comment]
@wofeifeileni I remember that the default data_root in StreamPETR is different from PETR.https://github.com/megvii-research/PETR/blob/f7525f93467a33707ef401c587a52d5e7b34de74/projects/configs/petrv2/petrv2_BEVseg.py#L164
You should modify it in the config and check the data_root during the generation process of pkl file.

**Comment by wofeifeileni** [comment]
Okay, thank you. I will check it.
