### ISSUE TITLE
ImportError: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Vaishnav-B** [exiawsh/StreamPETR#213]
warnings.warn(
/local/mnt2/workspace/vaisb/miniconda3/envs/vaisb_PyTorch_13/lib/python3.8/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory
  warn(f"Failed to load image Python extension: {e}")
Traceback (most recent call last):
  File "./tools/test.py", line 17, in <module>
    from mmdet3d.apis import single_gpu_test
  File "/local/mnt2/workspace/vaisb/StreamPETR/mmdetection3d/mmdet3d/apis/__init__.py", line 2, in <module>
    from .inference import (convert_SyncBN, inference_detector,
  File "/local/mnt2/workspace/vaisb/StreamPETR/mmdetection3d/mmdet3d/apis/inference.py", line 12, in <module>
    from mmdet3d.core import (Box3DMode, CameraInstance3DBoxes, Coord3DMode,
  File "/local/mnt2/workspace/vaisb/StreamPETR/mmdetection3d/mmdet3d/core/__init__.py", line 2, in <module>
    from .anchor import *  # noqa: F401, F403
  File "/local/mnt2/workspace/vaisb/StreamPETR/mmdetection3d/mmdet3d/core/anchor/__init__.py", line 2, in <module>
    from mmdet.core.anchor import build_prior_generator
  File "/local/mnt2/workspace/vaisb/miniconda3/envs/vaisb_PyTorch_13/lib/python3.8/site-packages/mmdet/core/__init__.py", line 3, in <module>
    from .bbox import *  # noqa: F401, F403
  File "/local/mnt2/workspace/vaisb/miniconda3/envs/vaisb_PyTorch_13/lib/python3.8/site-packages/mmdet/core/bbox/__init__.py", line 8, in <module>
    from .samplers import (BaseSampler, CombinedSampler,
  File "/local/mnt2/workspace/vaisb/miniconda3/envs/vaisb_PyTorch_13/lib/python3.8/site-packages/mmdet/core/bbox/samplers/__init__.py", line 12, in <module>
    from .score_hlr_sampler import ScoreHLRSampler
  File "/local/mnt2/workspace/vaisb/miniconda3/envs/vaisb_PyTorch_13/lib/python3.8/site-packages/mmdet/core/bbox/samplers/score_hlr_sampler.py", line 3, in <module>
    from mmcv.ops import nms_match
  File "/local/mnt2/workspace/vaisb/miniconda3/envs/vaisb_PyTorch_13/lib/python3.8/site-packages/mmcv/ops/__init__.py", line 2, in <module>
    from .active_rotated_filter import active_rotated_filter
  File "/local/mnt2/workspace/vaisb/miniconda3/envs/vaisb_PyTorch_13/lib/python3.8/site-packages/mmcv/ops/active_rotated_filter.py", line 10, in <module>
    ext_module = ext_loader.load_ext(
  File "/local/mnt2/workspace/vaisb/miniconda3/envs/vaisb_PyTorch_13/lib/python3.8/site-packages/mmcv/utils/ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/local/mnt2/workspace/vaisb/miniconda3/envs/vaisb_PyTorch_13/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory

Hey, I'm trying to run the StreamPETR model on PyTorch 1.13 but am running into this error
Previously I was using PyTorch 1.12 and that worked fine. Now I want to upgrade to PyTorch 1.13
Also wanted to ask about support for PyTorch 2.x. What changes need to be done for running StreamPETR with PyTorch 2.x

**Comment by haofuly** [comment]
@Vaishnav-B 
Have you ever solve this error? Thanks.

**Comment by Vaishnav-B** [comment]
> @Vaishnav-B Have you ever solve this error? Thanks.

@haofuly 
I haven't been able to solve it yet.

**Comment by haofuly** [comment]
> > @Vaishnav-B Have you ever solve this error? Thanks.
> 
> @haofuly I haven't been able to solve it yet.

What is the mistake you made? And how to solve this problem? I meet the same error as you.
Thanks.

**Comment by haofuly** [comment]
> > @Vaishnav-B Have you ever solve this error? Thanks.
> 
> @haofuly I haven't been able to solve it yet.

@Vaishnav-B 
I have solved it. The mistake lies in the Environment Setup Procedure. You must follow the instruction:
`pip install torch==1.9.0+cu111 torchvision==0.10.0+cu111 torchaudio==0.9.0 -f https://download.pytorch.org/whl/torch_stable.html`
rather than install torch using Pytorch official instruction. It's also OK to download the .whl files in https://download.pytorch.org/whl/torch_stable.html and install them manually.

**Comment by Vaishnav-B** [comment]
> > > @Vaishnav-B Have you ever solve this error? Thanks.
> > 
> > 
> > @haofuly I haven't been able to solve it yet.
> 
> @Vaishnav-B I have solved it. The mistake lies in the Environment Setup Procedure. You must follow the instruction: `pip install torch==1.9.0+cu111 torchvision==0.10.0+cu111 torchaudio==0.9.0 -f https://download.pytorch.org/whl/torch_stable.html` rather than install torch using Pytorch official instruction. It's also OK to download the .whl files in https://download.pytorch.org/whl/torch_stable.html and install them manually.

@haofuly 
I want to use PyTorch 1.13.1. It works for me on PyTorch 1.12.1 but I want to migrate to PyTorch 1.13.1
