### ISSUE TITLE
pip issue with MMCV

### ISSUE THREAD

**Issue by changliucoding** [exiawsh/StreamPETR#28]
Hi I installed required MMCV == 1.6.0 but when I run the train.py in tools folder I run into this issue. Is there a way to fix it? thanks!

Traceback (most recent call last):
  File "/home/Desktop/Git/StreamPETR/tools/train.py", line 21, in <module>
    from mmdet3d import __version__ as mmdet3d_version
  File "/home/anaconda3/envs/streampetr/lib/python3.8/site-packages/mmdet3d/__init__.py", line 21, in <module>
    assert (mmcv_version >= digit_version(mmcv_minimum_version)
AssertionError: MMCV==1.6.0 is used but incompatible. Please install mmcv>=2.0.0rc4, <2.1.0.

**Comment by exiawsh** [comment]
> Hi I installed required MMCV-full == 1.6.0 but when I run the train.py in tools folder I run into this issue. Is there a way to fix it? thanks!
> 
> Traceback (most recent call last): File "/home/Desktop/Git/StreamPETR/tools/train.py", line 21, in from mmdet3d import **version** as mmdet3d_version File "/home/anaconda3/envs/streampetr/lib/python3.8/site-packages/mmdet3d/**init**.py", line 21, in assert (mmcv_version >= digit_version(mmcv_minimum_version) AssertionError: MMCV==1.6.0 is used but incompatible. Please install mmcv>=2.0.0rc4, <2.1.0.

Check you mmdet3d version. You may require to re-install the mmdet3d.

**Comment by changliucoding** [comment]
> > Hi I installed required MMCV-full == 1.6.0 but when I run the train.py in tools folder I run into this issue. Is there a way to fix it? thanks!
> > Traceback (most recent call last): File "/home/Desktop/Git/StreamPETR/tools/train.py", line 21, in from mmdet3d import **version** as mmdet3d_version File "/home/anaconda3/envs/streampetr/lib/python3.8/site-packages/mmdet3d/**init**.py", line 21, in assert (mmcv_version >= digit_version(mmcv_minimum_version) AssertionError: MMCV==1.6.0 is used but incompatible. Please install mmcv>=2.0.0rc4, <2.1.0.
> 
> Check you mmdet3d version. You may require to re-install the mmdet3d.

Hi, thanks, and I had another issue. The full-dataset is too large for me now, so tried to run mini dataset first. I put everything as required in the folder. Then I tried to create info file. Then I had this issue, I wonder if you had the same error before.

ython tools/create_data_nusc.py --root-path ./data/nuscenes --out-dir ./data/nuscenes --extra-tag nuscenes2d --version v1.0
Traceback (most recent call last):
  File "tools/create_data_nusc.py", line 5, in <module>
    from data_converter import nuscenes_converter as nuscenes_converter
  File "/home/chang/Desktop/Git/StreamPETR/tools/data_converter/nuscenes_converter.py", line 14, in <module>
    from mmdet3d.core.bbox import points_cam2img
  File "/home/anaconda3/envs/streampetr/lib/python3.8/site-packages/mmdet3d/core/__init__.py", line 4, in <module>
    from .evaluation import *  # noqa: F401, F403
  File "/home/anaconda3/envs/streampetr/lib/python3.8/site-packages/mmdet3d/core/evaluation/__init__.py", line 4, in <module>
    from .kitti_utils import kitti_eval, kitti_eval_coco_style
  File "/home/anaconda3/envs/streampetr/lib/python3.8/site-packages/mmdet3d/core/evaluation/kitti_utils/__init__.py", line 2, in <module>
    from .eval import kitti_eval, kitti_eval_coco_style
  File "/home/anaconda3/envs/streampetr/lib/python3.8/site-packages/mmdet3d/core/evaluation/kitti_utils/eval.py", line 5, in <module>
    import numba
  File "/home/anaconda3/envs/streampetr/lib/python3.8/site-packages/numba/__init__.py", line 43, in <module>
    from numba.np.ufunc import (vectorize, guvectorize, threading_layer,
  File "/home/anaconda3/envs/streampetr/lib/python3.8/site-packages/numba/np/ufunc/__init__.py", line 3, in <module>
    from numba.np.ufunc.decorators import Vectorize, GUVectorize, vectorize, guvectorize
  File "/home/anaconda3/envs/streampetr/lib/python3.8/site-packages/numba/np/ufunc/decorators.py", line 3, in <module>
    from numba.np.ufunc import _internal
SystemError: initialization of _internal failed without raising an exception

**Comment by exiawsh** [comment]
Do not use conda install. Please follow our instructions:
git clone https://github.com/open-mmlab/mmdetection3d.git
cd mmdetection3d
git checkout v1.0.0rc6 
pip install -e .

**Comment by changliucoding** [comment]
> Do not use conda install. Please follow our instructions: git clone https://github.com/open-mmlab/mmdetection3d.git cd mmdetection3d git checkout v1.0.0rc6 pip install -e .

Indeed, I just realized I made a mistake when install mmdet3d, now I fixed this mistake.

**Comment by changliucoding** [comment]
> > from numba.np.ufunc import _internal
> 
> You don't follow our step by step instructions. So the version of some packages is wrong...

okay. I will uninstall everything and do it again. sorry for the inconvenience

**Comment by changliucoding** [comment]
> > from numba.np.ufunc import _internal
> 
> You don't follow our step by step instructions. So the version of some packages is wrong...

Hi I uninstalled the streampetr and reinstalled everything. But still have the same error. I had this 
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
absl-py                   1.4.0                    pypi_0    pypi
addict                    2.4.0                    pypi_0    pypi
anyio                     3.7.0                    pypi_0    pypi
argon2-cffi               21.3.0                   pypi_0    pypi
argon2-cffi-bindings      21.2.0                   pypi_0    pypi
arrow                     1.2.3                    pypi_0    pypi
asttokens                 2.2.1                    pypi_0    pypi
attrs                     23.1.0                   pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
black                     23.3.0                   pypi_0    pypi
bleach                    6.0.0                    pypi_0    pypi
ca-certificates           2023.01.10           h06a4308_0  
cachetools                5.3.1                    pypi_0    pypi
certifi                   2023.5.7                 pypi_0    pypi
cffi                      1.15.1                   pypi_0    pypi
chardet                   4.0.0                    pypi_0    pypi
click                     8.1.3                    pypi_0    pypi
comm                      0.1.3                    pypi_0    pypi
contourpy                 1.0.7                    pypi_0    pypi
cycler                    0.11.0                   pypi_0    pypi
debugpy                   1.6.7                    pypi_0    pypi
defusedxml                0.7.1                    pypi_0    pypi
descartes                 1.1.0                    pypi_0    pypi
exceptiongroup            1.1.1                    pypi_0    pypi
executing                 1.2.0                    pypi_0    pypi
fastjsonschema            2.17.1                   pypi_0    pypi
fire                      0.5.0                    pypi_0    pypi
flake8                    6.0.0                    pypi_0    pypi
fonttools                 4.39.4                   pypi_0    pypi
fqdn                      1.5.1                    pypi_0    pypi
google-auth               2.19.1                   pypi_0    pypi
google-auth-oauthlib      1.0.0                    pypi_0    pypi
grpcio                    1.54.2                   pypi_0    pypi
idna                      2.10                     pypi_0    pypi
imageio                   2.31.0                   pypi_0    pypi
importlib-metadata        6.6.0                    pypi_0    pypi
importlib-resources       5.12.0                   pypi_0    pypi
iniconfig                 2.0.0                    pypi_0    pypi
ipykernel                 6.23.1                   pypi_0    pypi
ipython                   8.12.2                   pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
ipywidgets                8.0.6                    pypi_0    pypi
isoduration               20.11.0                  pypi_0    pypi
jedi                      0.18.2                   pypi_0    pypi
jinja2                    3.1.2                    pypi_0    pypi
joblib                    1.2.0                    pypi_0    pypi
jsonpointer               2.3                      pypi_0    pypi
jsonschema                4.17.3                   pypi_0    pypi
jupyter                   1.0.0                    pypi_0    pypi
jupyter-client            8.2.0                    pypi_0    pypi
jupyter-console           6.6.3                    pypi_0    pypi
jupyter-core              5.3.0                    pypi_0    pypi
jupyter-events            0.6.3                    pypi_0    pypi
jupyter-server            2.6.0                    pypi_0    pypi
jupyter-server-terminals  0.4.4                    pypi_0    pypi
jupyterlab-pygments       0.2.2                    pypi_0    pypi
jupyterlab-widgets        3.0.7                    pypi_0    pypi
kiwisolver                1.4.4                    pypi_0    pypi
ld_impl_linux-64          2.38                 h1181459_1  
libffi                    3.4.4                h6a678d5_0  
libgcc-ng                 11.2.0               h1234567_1  
libgomp                   11.2.0               h1234567_1  
libstdcxx-ng              11.2.0               h1234567_1  
llvmlite                  0.36.0                   pypi_0    pypi
lyft-dataset-sdk          0.0.8                    pypi_0    pypi
markdown                  3.4.3                    pypi_0    pypi
markupsafe                2.1.3                    pypi_0    pypi
matplotlib                3.5.2                    pypi_0    pypi
matplotlib-inline         0.1.6                    pypi_0    pypi
mccabe                    0.7.0                    pypi_0    pypi
mistune                   2.0.5                    pypi_0    pypi
mmcls                     0.25.0                   pypi_0    pypi
mmcv-full                 1.6.0                    pypi_0    pypi
mmdet                     2.28.2                   pypi_0    pypi
mmdet3d                   1.0.0rc6                  dev_0    <develop>
mmsegmentation            0.30.0                   pypi_0    pypi
mypy-extensions           1.0.0                    pypi_0    pypi
nbclassic                 1.0.0                    pypi_0    pypi
nbclient                  0.8.0                    pypi_0    pypi
nbconvert                 7.4.0                    pypi_0    pypi
nbformat                  5.9.0                    pypi_0    pypi
ncurses                   6.4                  h6a678d5_0  
nest-asyncio              1.5.6                    pypi_0    pypi
networkx                  2.2                      pypi_0    pypi
notebook                  6.5.4                    pypi_0    pypi
notebook-shim             0.2.3                    pypi_0    pypi
numba                     0.53.0                   pypi_0    pypi
numpy                     1.24.3                   pypi_0    pypi
nuscenes-devkit           1.1.10                   pypi_0    pypi
oauthlib                  3.2.2                    pypi_0    pypi
opencv-python             4.7.0.72                 pypi_0    pypi
openssl                   1.1.1t               h7f8727e_0  
overrides                 7.3.1                    pypi_0    pypi
packaging                 23.1                     pypi_0    pypi
pandas                    2.0.2                    pypi_0    pypi
pandocfilters             1.5.0                    pypi_0    pypi
parso                     0.8.3                    pypi_0    pypi
pathspec                  0.11.1                   pypi_0    pypi
pexpect                   4.8.0                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    9.5.0                    pypi_0    pypi
pip                       23.0.1           py38h06a4308_0  
pkgutil-resolve-name      1.3.10                   pypi_0    pypi
platformdirs              3.5.1                    pypi_0    pypi
plotly                    5.14.1                   pypi_0    pypi
pluggy                    1.0.0                    pypi_0    pypi
plyfile                   0.9                      pypi_0    pypi
prettytable               3.7.0                    pypi_0    pypi
prometheus-client         0.17.0                   pypi_0    pypi
prompt-toolkit            3.0.38                   pypi_0    pypi
protobuf                  4.23.2                   pypi_0    pypi
psutil                    5.9.5                    pypi_0    pypi
ptyprocess                0.7.0                    pypi_0    pypi
pure-eval                 0.2.2                    pypi_0    pypi
pyasn1                    0.5.0                    pypi_0    pypi
pyasn1-modules            0.3.0                    pypi_0    pypi
pycocotools               2.0.6                    pypi_0    pypi
pycodestyle               2.10.0                   pypi_0    pypi
pycparser                 2.21                     pypi_0    pypi
pyflakes                  3.0.1                    pypi_0    pypi
pygments                  2.15.1                   pypi_0    pypi
pyparsing                 3.0.9                    pypi_0    pypi
pyquaternion              0.9.9                    pypi_0    pypi
pyrsistent                0.19.3                   pypi_0    pypi
pytest                    7.3.1                    pypi_0    pypi
python                    3.8.16               h7a1cb2a_3  
python-dateutil           2.8.2                    pypi_0    pypi
python-json-logger        2.0.7                    pypi_0    pypi
pytz                      2023.3                   pypi_0    pypi
pywavelets                1.4.1                    pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
pyzmq                     25.1.0                   pypi_0    pypi
qtconsole                 5.4.3                    pypi_0    pypi
qtpy                      2.3.1                    pypi_0    pypi
readline                  8.2                  h5eee18b_0  
requests-oauthlib         1.3.1                    pypi_0    pypi
rfc3339-validator         0.1.4                    pypi_0    pypi
rfc3986-validator         0.1.1                    pypi_0    pypi
rsa                       4.9                      pypi_0    pypi
scikit-image              0.19.3                   pypi_0    pypi
scikit-learn              1.2.2                    pypi_0    pypi
scipy                     1.10.1                   pypi_0    pypi
send2trash                1.8.2                    pypi_0    pypi
setuptools                67.8.0           py38h06a4308_0  
shapely                   1.8.5                    pypi_0    pypi
six                       1.16.0                   pypi_0    pypi
sniffio                   1.3.0                    pypi_0    pypi
sqlite                    3.41.2               h5eee18b_0  
stack-data                0.6.2                    pypi_0    pypi
tenacity                  8.2.2                    pypi_0    pypi
tensorboard               2.13.0                   pypi_0    pypi
tensorboard-data-server   0.7.0                    pypi_0    pypi
terminado                 0.17.1                   pypi_0    pypi
terminaltables            3.1.10                   pypi_0    pypi
threadpoolctl             3.1.0                    pypi_0    pypi
tifffile                  2023.4.12                pypi_0    pypi
tinycss2                  1.2.1                    pypi_0    pypi
tk                        8.6.12               h1ccaba5_0  
tomli                     2.0.1                    pypi_0    pypi
torch                     1.9.0+cu111              pypi_0    pypi
torchaudio                0.9.0                    pypi_0    pypi
torchvision               0.10.0+cu111             pypi_0    pypi
tornado                   6.3.2                    pypi_0    pypi
tqdm                      4.65.0                   pypi_0    pypi
traitlets                 5.9.0                    pypi_0    pypi
trimesh                   2.35.39                  pypi_0    pypi
typing-extensions         4.6.3                    pypi_0    pypi
tzdata                    2023.3                   pypi_0    pypi
uri-template              1.2.0                    pypi_0    pypi
urllib3                   1.26.16                  pypi_0    pypi
wcwidth                   0.2.6                    pypi_0    pypi
webcolors                 1.13                     pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
werkzeug                  2.3.4                    pypi_0    pypi
wheel                     0.38.4           py38h06a4308_0  
widgetsnbextension        4.0.7                    pypi_0    pypi
xz                        5.4.2                h5eee18b_0  
yapf                      0.33.0                   pypi_0    pypi
zipp                      3.15.0                   pypi_0    pypi
zlib                      1.2.13               h5eee18b_0  
in my conda. I wonder if this is correct so I can run create info file step. Also could this becasue I am using mini dataset instead of full dataset?

**Comment by exiawsh** [comment]
I'm sure mini dataset is ok. Because I'm debugging using mini dataset right now.

**Comment by changliucoding** [comment]
> I'm sure mini dataset is ok. Because I'm debugging using mini dataset right now.

![Screenshot from 2023-06-05 15-51-21](https://github.com/exiawsh/StreamPETR/assets/133587429/d8e5fa30-5da5-40c0-9efb-23fa0811721a)
Hi put the data structure as the instructions like this. is this error happening because of Numba?

**Comment by changliucoding** [comment]
> I have uploaded the pkl files of mini-version. Please check: https://github.com/exiawsh/storage/releases/download/v1.0/nuscenes2d_temporal_infos_train_mini.pkl https://github.com/exiawsh/storage/releases/download/v1.0/nuscenes2d_temporal_infos_val_mini.pkl

thanks! but it seems that the error is because of my numpy and numba version. May I ask what version are you using both of them? This time I really follow the instruction but still not working. ( i download mini.pkl thanks for the help!)

**Comment by exiawsh** [comment]
numpy: '1.23.3'
numba: '0.53.0'
