### ISSUE TITLE
How to turn off distributed training?

### ISSUE THREAD

**Issue by changliucoding** [exiawsh/StreamPETR#29]
I'm trying your project with a single Nvidia graphics card, but it seems that the train.sh file is using distributed training, I tried changing it to

#!/usr/bin/env bash

CONFIG=$1

PYTHONPATH="$(dirname $0)/..":$PYTHONPATH \
python $(dirname "$0")/train.py \
    $CONFIG \
    --seed 0

but I got an error 

Traceback (most recent call last):
  File "tools/train.py", line 263, in <module>
    main()
  File "tools/train.py", line 251, in main
    custom_train_model(
  File "/home/Desktop/Git/StreamPETR/projects/mmdet3d_plugin/core/apis/train.py", line 30, in custom_train_model
    custom_train_detector(
  File "/home/Desktop/Git/StreamPETR/projects/mmdet3d_plugin/core/apis/mmdet_train.py", line 203, in custom_train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/anaconda3/envs/streampetr/lib/python3.8/site-packages/mmcv/runner/iter_based_runner.py", line 126, in run
    self.call_hook('before_run')
  File "/home/anaconda3/envs/streampetr/lib/python3.8/site-packages/mmcv/runner/base_runner.py", line 317, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/anaconda3/envs/streampetr/lib/python3.8/site-packages/mmcv/runner/dist_utils.py", line 135, in wrapper
    return func(*args, **kwargs)
  File "/home/anaconda3/envs/streampetr/lib/python3.8/site-packages/mmcv/runner/hooks/logger/tensorboard.py", line 47, in before_run
    from torch.utils.tensorboard import SummaryWriter
  File "/home/anaconda3/envs/streampetr/lib/python3.8/site-packages/torch/utils/tensorboard/__init__.py", line 4, in <module>
    LooseVersion = distutils.version.LooseVersion
AttributeError: module 'distutils' has no attribute 'version'

I have put all required files into ckpt and data already, but still could not train or test visualize. I might need your help, thanks!

**Comment by exiawsh** [comment]
Check your setuptools verision: 45.2.0
I need to sleep now. If you have other question, I will reply you tomorrow.
