### ISSUE TITLE
How to eval model every epoch?

### ISSUE THREAD

**Issue by dop0** [exiawsh/StreamPETR#35]
Hello, I change the interval in config to num_iters_per_epoch, but i got error after first eval.
`evaluation = dict(interval=num_iters_per_epoch, pipeline=test_pipeline) `
```
[                                                  ] 2/6019, 0.6 task/s, elapsed: 3s, ETA:  9675s/app/StreamPETR/projects/mmdet3d_plugin/core/bbox/coders/nms_free_coder.py:67: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  self.post_center_range = torch.tensor(self.post_center_range, device=scores.device)
[                                                  ] 6/6019, 1.7 task/s, elapsed: 3s, ETA:  3456s/app/StreamPETR/projects/mmdet3d_plugin/core/bbox/coders/nms_free_coder.py:67: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  self.post_center_range = torch.tensor(self.post_center_range, device=scores.device)
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 6020/6019, 16.8 task/s, elapsed: 358s, ETA:     0sTraceback (most recent call last):
  File "tools/train.py", line 263, in <module>
    main()
  File "tools/train.py", line 251, in main
    custom_train_model(
  File "/app/StreamPETR/projects/mmdet3d_plugin/core/apis/train.py", line 30, in custom_train_model
    custom_train_detector(
  File "/app/StreamPETR/projects/mmdet3d_plugin/core/apis/mmdet_train.py", line 203, in custom_train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/app/conda/lib/python3.8/site-packages/mmcv/runner/iter_based_runner.py", line 144, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "/app/conda/lib/python3.8/site-packages/mmcv/runner/iter_based_runner.py", line 64, in train
    outputs = self.model.train_step(data_batch, self.optimizer, **kwargs)
  File "/app/conda/lib/python3.8/site-packages/mmcv/parallel/distributed.py", line 63, in train_step
    output = self.module.train_step(*inputs[0], **kwargs[0])
  File "/app/conda/lib/python3.8/site-packages/mmdet/models/detectors/base.py", line 248, in train_step
    losses = self(**data)
  File "/app/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/app/conda/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 233, in new_func
    output = old_func(*new_args, **new_kwargs)
  File "/app/StreamPETR/projects/mmdet3d_plugin/models/detectors/petr3d.py", line 217, in forward
    return self.forward_train(**data)
  File "/app/StreamPETR/projects/mmdet3d_plugin/models/detectors/petr3d.py", line 269, in forward_train
    losses = self.obtain_history_memory(gt_bboxes_3d,
  File "/app/StreamPETR/projects/mmdet3d_plugin/models/detectors/petr3d.py", line 130, in obtain_history_memory
    loss = self.forward_pts_train(gt_bboxes_3d[i],
  File "/app/StreamPETR/projects/mmdet3d_plugin/models/detectors/petr3d.py", line 189, in forward_pts_train
    outs = self.pts_bbox_head(location, img_metas, topk_indexes, **data)
  File "/app/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/app/StreamPETR/projects/mmdet3d_plugin/models/dense_heads/streampetr_head.py", line 581, in forward
    self.pre_update_memory(data)
  File "/app/StreamPETR/projects/mmdet3d_plugin/models/dense_heads/streampetr_head.py", line 330, in pre_update_memory
    self.memory_timestamp += data['timestamp'].unsqueeze(-1).unsqueeze(-1)
RuntimeError: output with shape [1, 1280, 1] doesn't match the broadcast shape [4, 1280, 1]
```

**Comment by exiawsh** [comment]
Evaluating the model every epoch is not supported now. You need to save all the checkpoints. And test them after training.

**Comment by dop0** [comment]
I see, thanks for your quick reply and excellent work.

**Comment by fbcotter** [comment]
> Evaluating the model every epoch is not supported now. You need to save all the checkpoints. And test them after training.

Why not? Is the issue hard to fix? Seems like it's a shame to drop that ability

**Comment by exiawsh** [comment]
@fbcotter Thanks, I will try to fix it in the next month.

**Comment by exiawsh** [comment]
@fbcotter Thanks for the advice, this issue has been fixed now. I was busy with my PhD and job applications last month.
