### ISSUE TITLE
Can't output .pkl files during data processing

### ISSUE THREAD

**Issue by dszpr** [exiawsh/StreamPETR#94]
Hi, I can't generate nuscenes2d_infos_temporal_{train,val}.pkl files by using commands below:

```
root@64efd562e410:/workspace/StreamPETR# python tools/create_data_nusc.py --root-path /workspace/datasets_nuscenes --out-dir /workspace/data_nuscenes2d --extra-tag nuscenes2d --version v1.0-mini
======
Loading NuScenes tables for version v1.0-mini...
23 category,
8 attribute,
4 visibility,
911 instance,
12 sensor,
120 calibrated_sensor,
31206 ego_pose,
8 log,
10 scene,
404 sample,
31206 sample_data,
18538 sample_annotation,
4 map,
Done loading in 0.489 seconds.
======
Reverse indexing ...
Done reverse indexing in 0.1 seconds.
======
total scene num: 10
exist scene num: 10
train scene: 8, val scene: 2
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 404/404, 3.3 task/s, elapsed: 124s, ETA:     0s
train sample: 323, val sample: 81
root@64efd562e410:/workspace/StreamPETR# cd ..
root@64efd562e410:/workspace# cd data_nuscenes2d/
root@64efd562e410:/workspace/data_nuscenes2d# ls
root@64efd562e410:/workspace/data_nuscenes2d#
```

No error or bug appeared during the data-processing. However, the output directory is empty after data-processing. And I don't know what's going wrong.
Could I have some advice? Thanks so much.

**Comment by dszpr** [comment]
@exiawsh @okkkkxhj @yingfei1016

**Comment by dszpr** [comment]
I found that the .pkl files are output to /workspace/datasets_nuscenes, which is the original datasets directory instead of the output directory I specified. Anyway, the problem has been solved.

**Comment by BaophanN** [comment]
Hi, i do not understand why I could not preprocess annotation for nuScenes mini despite running the same command as yours.
```
(lanesegnet) root@fd753aaa3ca9:/workspace/source/WidthFormer/StreamPETR# python tools
/create_data_nusc.py --root-path ./data/nuscenes --out-dir ./data/nuscenes --extra-ta
g nuscenes2d --version v1.0-mini
======
Loading NuScenes tables for version v1.0-mini...
25 category,
12 attribute,
4 visibility,
911 instance,
6 sensor,
50 calibrated_sensor,
650 ego_pose,
44 log,
10 scene,
50 sample,
650 sample_data,
18538 sample_annotation,
4 map,
Done loading in 0.183 seconds.
======
Reverse indexing ...
Traceback (most recent call last):
  File "tools/create_data_nusc.py", line 74, in <module>
    nuscenes_data_prep(
  File "tools/create_data_nusc.py", line 27, in nuscenes_data_prep
    nuscenes_converter.create_nuscenes_infos(
  File "/workspace/source/WidthFormer/StreamPETR/tools/data_converter/nuscenes_converter.py", line 45, in create_nuscenes_infos
    nusc = NuScenes(version=version, dataroot=root_path, verbose=True)
  File "/opt/conda/envs/lanesegnet/lib/python3.8/site-packages/nuscenes/nuscenes.py", line 124, in __init__
    self.__make_reverse_index__(verbose)
  File "/opt/conda/envs/lanesegnet/lib/python3.8/site-packages/nuscenes/nuscenes.py", line 171, in __make_reverse_index__
    record['category_name'] = self.get('category', inst['category_token'])['name']
  File "/opt/conda/envs/lanesegnet/lib/python3.8/site-packages/nuscenes/nuscenes.py", line 216, in get
    return getattr(self, table_name)[self.getind(table_name, token)]
  File "/opt/conda/envs/lanesegnet/lib/python3.8/site-packages/nuscenes/nuscenes.py", line 225, in getind
    return self._token2ind[table_name][token]
KeyError: 'bb867e2064014279863c71a29b1eb381'
```
Can you help me solve this problem? Thank you
