### ISSUE TITLE
SystemError: initialization of _internal failed without raising an exception

### ISSUE THREAD

**Issue by SniperZhao** [exiawsh/StreamPETR#99]
I tried to run "python tools/create_data_nusc.py --root-path ./data/nuscenes --out-dir ./data/nuscenes --extra-tag nuscenes2d --version v1.0" and got this error log:
```
Traceback (most recent call last):
  File "tools/create_data_nusc.py", line 5, in <module>
    from data_converter import nuscenes_converter as nuscenes_converter
  File "/mnt/yuan_zhao_cfs/zhaoyuan/001.code/StreamPETR/tools/data_converter/nuscenes_converter.py", line 14, in <module>
    from mmdet3d.core.bbox import points_cam2img
  File "/mnt/yuan_zhao_cfs/zhaoyuan/001.code/StreamPETR/mmdetection3d/mmdet3d/core/__init__.py", line 4, in <module>
    from .evaluation import *  # noqa: F401, F403
  File "/mnt/yuan_zhao_cfs/zhaoyuan/001.code/StreamPETR/mmdetection3d/mmdet3d/core/evaluation/__init__.py", line 4, in <module>
    from .kitti_utils import kitti_eval, kitti_eval_coco_style
  File "/mnt/yuan_zhao_cfs/zhaoyuan/001.code/StreamPETR/mmdetection3d/mmdet3d/core/evaluation/kitti_utils/__init__.py", line 2, in <module>
    from .eval import kitti_eval, kitti_eval_coco_style
  File "/mnt/yuan_zhao_cfs/zhaoyuan/001.code/StreamPETR/mmdetection3d/mmdet3d/core/evaluation/kitti_utils/eval.py", line 5, in <module>
    import numba
  File "/home/yuan.zhao/003.tools/miniconda3/envs/streampetr/lib/python3.8/site-packages/numba/__init__.py", line 43, in <module>
    from numba.np.ufunc import (vectorize, guvectorize, threading_layer,
  File "/home/yuan.zhao/003.tools/miniconda3/envs/streampetr/lib/python3.8/site-packages/numba/np/ufunc/__init__.py", line 3, in <module>
    from numba.np.ufunc.decorators import Vectorize, GUVectorize, vectorize, guvectorize
  File "/home/yuan.zhao/003.tools/miniconda3/envs/streampetr/lib/python3.8/site-packages/numba/np/ufunc/decorators.py", line 3, in <module>
    from numba.np.ufunc import _internal
SystemError: initialization of _internal failed without raising an exception
```

version of numpy is 1.24.4
version of numba is 0.53.0

**Comment by SniperZhao** [comment]
I use Numpy==1.21.4 and Numba==0.53.0, it works.
https://stackoverflow.com/questions/70148065/numba-needs-numpy-1-20-or-less-for-shapley-import

**Comment by SniperZhao** [comment]
I use Numpy==1.21.4 and Numba==0.53.0, it works.
https://stackoverflow.com/questions/70148065/numba-needs-numpy-1-20-or-less-for-shapley-import
